[platformio]
default_envs = esp32s3
src_dir = main

[env:esp32s3]
platform = espressif32 @ 5.4.0
platform_packages =
    framework-espidf @ ~3.40405.0
    tool-cmake @ 3.30.2

board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
framework = espidf

board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv

board_build.flash_mode = dio
board_build.f_flash = 40000000L
board_build.memory_type = dio_opi

board_build.f_cpu = 240000000L

monitor_speed = 115200

build_flags = -DNO_ESP32WROOM32_CRYPT -DCORE_DEBUG_LEVEL=5